language: node_js
node_js:
 — “stable”
branches:
 only:
 — Dev
before_script:
 — npm install -g @ionic/cli
 — npm install 
 — npm ci 
script:
 — ionic build 
after_success:
— rm -rf /tmp/IgrejaApp
— git clone  https://github.com/andreferreiratrindade/andreferreiratrindade.github.io.git --branch master /tmp/IgrejaApp/
— cp -r www/* /tmp/IgrejaApp/
— cd /tmp/Igreja/
— git config user.email "andreferreiratrindade@gmail.com"
— git config user.name "André"
— git add --all
— git commit -a -m "deploy"
— git checkout -b master
— git push --force origin master
deploy:
 provider: pages
 skip-cleanup: true
 keep-history: true
 github-token: $GITHUB_TOKEN
 on:
   branch: Dev
 local_dir: www