language: node_js
node_js:
 — “stable”
branches:
 only:
 — Dev
before_script:
 — npm install -g @ionic/cli
 — npm install 
 — npm ci 
script:
 — ionic build 
 — git clone --recursive -b gh-pages https://github.com/andreferreiratrindade/andreferreiratrindade.github.io.git /tmp/IgrejaApp/
 — cp -r www*/ /tmp/IgrejaApp/
 — cd /tmp/Igreja/
 — git add .
 — git commit -m "deploy"
 — git push -u
  
deploy:
 provider: pages
 skip-cleanup: true
 keep-history: true
 github-token: $GITHUB_TOKEN
 on:
   branch: Dev
 local_dir: www