language: node_js
node_js:
 — “stable”
branches:
 only:
 — Dev
before_script:
 — npm install -g @ionic/cli
 — npm install 
 — npm ci 
script:
 — ionic build --prod -- --base-href="https://andreferreiratrindade/andreferreiratrindade.github.io/IgrejaAppTeste/"
 — rm -rf public
 — mkdir public
 — cp -r www/* public
deploy:
 provider: pages
 skip-cleanup: true
 keep-history: true
 github-token: $GITHUB_TOKEN
 on:
   branch: Dev
 local_dir: www