version: 2

machine:
    environment:
          ANDROID_HOME: /usr/local/android-sdk-linux
          JAVA6_HOME: /usr/lib/jvm/java-6-openjdk-amd64
    java:
        version: openjdk8
dependencies:
    override:
            - echo y | sudo apt-get update
            - echo y | sudo apt-get install libpango-1.0-0
            - echo y | sudo apt-get install openjdk-6-jre

            - echo y | android update sdk --no-ui --all --filter tools,platform-tools,build-tools-23.0.3,android-23,extra-google-m2repository,extra-google-google_play_services,extra-android-support
            - ANDROID_HOME=/usr/local/android-sdk-linux ./gradlew dependencies      
jobs:
  build:     
    docker:
    - image: beevelop/ionic 
    steps:
    - checkout
    - run:
          name: Define Environment Variables and update JAVA_HOME and PATH at Runtime
          command: |
            echo 'Even though we are using tag jdk8u152-b16, the location where JAVA_HOME is, is named jdk8u144-b01'
            echo 'This is being fixed in subsequent versions of the JDK'
            echo 'export JAVA_VERSION=jdk8u144-b01'                               >> ${BASH_ENV}
            echo 'export JAVA_HOME=/opt/java/openjdk/'                            >> ${BASH_ENV}
            echo 'export PATH=${JAVA_HOME}/bin:${PATH}'                           >> ${BASH_ENV}
            echo 'export BASEDIR=${PWD}'                                          >> ${BASH_ENV}
            echo 'export SCRIPTS_LIB_DIR=${BASEDIR}/build/x86_64/linux_macos/lib' >> ${BASH_ENV}
            echo 'export MX=${BASEDIR}/mx/mx'                                     >> ${BASH_ENV}
            echo 'export JDK_GRAAL_FOLDER_NAME=jdk8-with-graal'                   >> ${BASH_ENV}
            echo 'export GRAAL_JVMCI_8_TAG=master'                                >> ${BASH_ENV}
            echo 'export BUILD_ARTIFACTS_DIR=${BASEDIR}/${JDK_GRAAL_FOLDER_NAME}' >> ${BASH_ENV}
            echo 'export RUN_TESTS="true"'                                        >> ${BASH_ENV}
            source ${BASH_ENV}
    - run:
        name: Install node modules
        command: npm install
    - run:
        name: Building android
        command: ionic cordova build android
    - store_artifacts:
        path: platforms/android/build/outputs/apk/android-debug.apk