version: 2

jobs:
  build:
    environment:
      JVM_OPTS: -Xmx3200m
    docker:
      - image: beevelop/ionic
    steps:
      - checkout
      - run:
          name: Configurando Java
          command: export JAVA_HOME=/usr/lib/jvm/jdk1.8.0_241/jre
      - run:
          name: Install node modules
          command: npm install
      - run:
          name: Building android
          command: ionic cordova build android
      - store_artifacts:
          path: platforms/android/build/outputs/apk/android-debug.apk