language: node_js
node_js:
 — “8.9.4”
branches:
 only:
 — Dev
before_script:
 — npm install -g ionic
 — npm ci 
script:
 — ionic build --prod -- --base-href ./
deploy:
 provider: pages
 skip-cleanup: true
 keep-history: true
 on:
   branch: Dev
 local_dir: www